version: '2'

services:

  redis:
     image: amm/redis
     build:
       context: docker/redis

  django:
    image: amm/django
    build: .
    volumes:
      - ./src:/opt/amm/src
      - ./htmlcov:/opt/amm/htmlcov
    expose:
      - "8000"
    depends_on:
      - "redis"
    command: gunicorn --reload -w 2 -b :8000 --chdir /opt/amm/src/ --access-logfile - config.wsgi:application

  nginx:
    image: amm/nginx
    build:
       context: docker/nginx
    ports:
      - "127.0.0.1:8888:80"
    depends_on:
      - "django"
