version: '2'

services:

  redis:
    image: library/redis

  django:
    image: epflidevelop/amm:latest
    volumes:
      - ./src:/opt/amm/src
      - ./htmlcov:/opt/amm/htmlcov
    environment:
      SECRET_KEY: ${SECRET_KEY}
      TEST_CORRECT_PWD: ${TEST_CORRECT_PWD}
      TEST_WRONG_PWD: ${TEST_WRONG_PWD}
      TEST_USERNAME: ${TEST_USERNAME}
      LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      LDAP_USER_SEARCH_ATTR: ${LDAP_USER_SEARCH_ATTR}
      LDAP_SERVER: ${LDAP_SERVER}
      CACHE_REDIS_LOCATION: ${CACHE_REDIS_LOCATION}
      CACHE_REDIS_CLIENT_CLASS: ${CACHE_REDIS_CLIENT_CLASS}
      AMM_ENVIRONMENT: ${AMM_ENVIRONMENT}

    expose:
      - "8000"
    links:
      - redis
    command: --reload -w 1 -b :8000 --chdir /opt/amm/src/ --access-logfile - config.wsgi:application
    entrypoint: gunicorn

  nginx:
    image: library/nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "127.0.0.1:8888:80"
    links:
      - django
